import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const userPrompt = body.prompt;

    const systemPrompt = `
You are a UI planner.
Return ONLY valid JSON.
Do not add explanations.

Return this format:
{
  "layout": "single-column",
  "components": [
    {
      "type": "Card",
      "props": {
        "title": "string",
        "content": "string"
      }
    },
    {
      "type": "Button",
      "props": {
        "label": "string"
      }
    }
  ]
}
`;

    const fullPrompt = `${systemPrompt}\n${userPrompt}`;

    // Call Gemini via the GoogleGenAI client
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: fullPrompt,
    });

    // Ensure rawOutput is always a string
    const rawOutput: string = response.text ?? "";
    console.log("RAW AI OUTPUT:", rawOutput);

    // --- ONLY CHANGE: sanitize output ---
    const cleanedOutput = rawOutput
      .replace(/```json/gi, "")
      .replace(/```/g, "")
      .trim();
    // ------------------------------------

    let plan;
    try {
      plan = JSON.parse(cleanedOutput);
    } catch (error) {
      console.error("JSON Parse Error:", error);

      // Fallback plan if AI output is invalid
      plan = {
        layout: "single-column",
        components: [
          { type: "Card", props: { title: "Default Card", content: "AI failed to generate content." } },
          { type: "Button", props: { label: "Default Button" } },
        ],
      };
    }

    const code = `
<Card title="${plan.components[0].props.title}">
  <p>${plan.components[0].props.content}</p>
</Card>

<Button label="${plan.components[1].props.label}" />
`;

    return NextResponse.json({
      plan,
      code,
      explanation: "Generated by Gemini",
    });

  } catch (err) {
    console.error("API Error:", err);

    // Always return valid JSON on error
    return NextResponse.json({
      plan: {
        layout: "single-column",
        components: [
          { type: "Card", props: { title: "Error Card", content: "Something went wrong." } },
          { type: "Button", props: { label: "Error Button" } },
        ],
      },
      code: `<Card title="Error Card"><p>Something went wrong.</p></Card><Button label="Error Button" />`,
      explanation: "API failed to generate content",
    }, { status: 500 });
  }
}
